### ISSUE TITLE
Adding an intro/outro clip

### ISSUE THREAD

**Issue by tanzaho** [h2non/videoshow#23]
Hi h2non,

Thanks for this wonderful script. I'd like to add intro/outro video clips to my videoshows. 
I tried to use the input() method but with no luck. Here is what I tried :  
```
var intro = "shared/intro.mp4";
var logo = 'shared/logo.png';
var mp3File = rootFolder + 'myAudio.mp3';
var loopTime = 15;
var images = [
  'step_1.png',
  'step_2.png',
  'step_3.png'
];
var videoOptions = {
      fps: 25,
      loop: loopTime, // seconds
      //loop: 5, // seconds
      transition: true,
      transitionDuration: 1, // seconds
      videoBitrate: 1024,
      videoCodec: 'libx264',
      size: '640x?',
      audioBitrate: '128k',
      audioChannels: 2,
      format: 'mp4'
    }

    var audioParams = {
      fade: true,
      delay: 2 // seconds
    }
videoshow(images, videoOptions)
  .input(intro)
  .audio(mp3File, audioParams)
  .logo(logo)
  .save(rootFolder + 'video.mp4')
  .on('start', function (command) {
    console.log('ffmpeg process started:', command)
  })
  .on('error', function (err, stdout, stderr) {
    console.error('Error:', err)
    console.error('ffmpeg stderr:', stderr)
  })
  .on('end', function (output) {
    console.error('Video created in:', output)
  })
```
The file runs smoothly however, the intro is not appended to the begginning as I had expected. Here is log (some filenames might have changed since I adapted the example for readability purposes) : 

```
ffmpeg process started: ffmpeg -i C:\Users\STEPHA~1\AppData\Local\Temp\videoshow-1eea30e5-af
db-48aa-addc-9785730f5ff9 -i C:\Users\STEPHA~1\AppData\Local\Temp\videoshow-42c55feb-986c-42
7a-910f-216f3d1fb9fe -i C:\Users\STEPHA~1\AppData\Local\Temp\videoshow-49c56b42-70cf-4b4f-be
8b-56514d1defc5 -i C:\Users\STEPHA~1\AppData\Local\Temp\videoshow-7a1a29df-bac7-483b-a219-48
7ba160b802 -y -filter_complex concat=n=4:v=1:a=0 episodes/713/video.mp4

ffmpeg process started: ffmpeg -i C:\Users\STEPHA~1\AppData\Local\Temp\videoshow-334ba015-7b
d1-42e3-9fcf-e725f434b0c4 -itsoffset 2 -i episodes/713/myAudio.mp3 -i shared/intro.mp4 -y -b:a 1
28k -ac 2 -r 25 -b:v 1024k -vcodec libx264 -filter:v scale=w=640:h=trunc(ow/a/2)*2 -f mp4 -m
ap 0:0 -map 1:0 -t 53.228833333333334 -af afade=t=in:ss=0:st=2:d=3 -af afade=t=out:st=50.228
833333333334:d=3 episodes/713/video.mp4

ffmpeg process started: ffmpeg -i C:\Users\STEPHA~1\AppData\Local\Temp\videoshow-334ba015-7b
d1-42e3-9fcf-e725f434b0c4 -i shared/logo.png -y -filter_complex [0:v][1:v]overlay=10:10:e
nable=between(t\,10\,43) episodes/713/video.mp4
Video created in: episodes/713/video.mp4
```

Do you have any indications on how to correctly use 'input' ?

**Comment by h2non** [comment]
Seems like this is due to the input type mapping in ffmpeg. `videoshow` wasn't initially designed to support video and images inputs together, but only images and optionally, audio. You can add intro and ending phases, but only using images.

If you need to create a video based on a composition of different type sources, such as images and other video chunks, I would recommend you to split the process in two phases: firstly, create a slideshow video using `videoshow` and only images as input, and then, using the raw [`ffmpeg`](https://github.com/h2non/videoshow#videoshowffmpeg) API, create another video based on the composition of a custom intro video, then the previous slideshow you created before and optionally, a custom ending video. Also, you should probably add the audio in this second phase too.

BTW, if you can find another more convenient solution using only `videoshow`, I would accept any improvement in that sense via PR.

**Comment by tanzaho** [comment]
I decided to use ffmpeg-fluent to merge the intro/outro files at the end of the process.
